### ISSUE TITLE
Yaptığınzı işe bakmıyor musunuz hiç.

### ISSUE THREAD

**Issue by mustafat0k** [ipara/ipara-php#3]
Ya sizin gibi küçük firmaları kullandığım güne nalet olsun ya.
İşimizvar gücümüz var yetiştirmeye çalışıyoruz verdiğiniz hizmet oranında bile baş ağrıtmıyorsunuz. 

Kendiniz test etmiyor musunuz demolarınız bile patlıyor.  İşe yaramaz bir dökümantasyonunuz var biraz paypal iyzico bakıp öğrenin işi yapan nasıl yapıyor.

**Comment by ugurarici** [comment]
Burada bir sorun tanımı yok, yer kaplamasına gerek yok. Deponun bir bekçisi olsa bunu kaldırsa ya da bu tip durumların yaşanmaması için kontrollerde bulunsa iyi olur.

**Comment by mustafat0k** [comment]
Sorun paketin yılları aşmış olması ve standartların çok dışında olması. Firmanın avukatı isen sorunlarını  sana anlatayım. 🗡️  burası yarım bir inşaat mı ki bekçisi olsun. 
Kontrollerde bulunulması gereken tek şey reponun güncelliği.

**Comment by ugurarici** [comment]
Hâlâ teknik bir mesele yok. Demagoji yerine teknik sorun tanımlanması, hata yaşanıyorsa nasıl yaşandığının açıklanması vs gerekiyor. Evet içeride çok kötü bir kod var. PHP 4 standartlarında sınıflar yazılmış, kod stili berbat vs. Github'da bunları teknik şekilde açıklayabilirsin ama "küçük firmaları kullandığım güne nalet olsun" diyemeyiz. Onu müşteri hizmetlerine falan söylemek gerekir. Her deponun bir bekçisi olur genelde, "maintainer" dedikleri hani. Özetle goygoy değil çözüm için konuşmak lazım.

Mesela bu paketin içeriğini günümüz standartlarında OOP kullanımı ve bağımlılık sızdırmaya uygun şekilde güncelledik ve kullanıyoruz. Teknik sıkıntının ne olduğunu anlasak gönderebilirdik. Ya da buranın bir bekçisi olduğuna inansak pull request göndermeyi düşünebilirdik. Neyse, jargon zamanla oturacaktır umarım. Kolay gelsin.

**Comment by mustafat0k** [comment]
Kendi yorumunla çelişiyorsun bende mecburen düzenledim kullanıyorum. Bak sorunlarını saydın . Demekki haklıymışım değil mi canım benim ? Tek tek saymaya lüzum yokmuş boş gürültü çıkarıyormuşsun ve  herşey ortada zaten neyin tekniğinden bahsediyorsun? Lan 10 yıla yakın bu işteyim jargon oturacaktır diyor aklına yandığım kavramı kendisinin bildiğini sanıyor. Her kavramın ingilizcedeki lügatı bellidir türkçeye olduğu gibi çevirirsen hiçbirşey anlatamazsın **bekçi guard'dır maintainer ile ifade ettiği şey aynı değildir.** Zamanla öğrenirsin merak etme. 

Belki hayatında benim kadar çok ve gelişmiş proje almamışsındır kullanmadığım framework yok ben seninle dalga geçiyorum kütüphane yazmışlar demo gibi hiçbir ödeme sisteminde olmayan dolaylı yollar var composer yok MVC dahil edilemiyor ne oop güncellemesi her dosyayı ayrı parçalara bölüp _namespace eklemişsinizdir en fazla ne gürültü yapıyorsun._
Neye içerlediysen böyle zoruna gitmişse artık. İlk yorumda gayet açık. _Bende laravel paketine çevirdim senin gibiler kullanacaksa public'te etmem._

**Comment by ugurarici** [comment]
Bak öğreniyorsun buraya teknik meseleleri yazmayı. Zamanla oluyor işte aferin :)

**Comment by mustafat0k** [comment]
Haha komik çocuksun vesselam. Yanımda olsan daha çok şey öğretirdim de nasiplendiğin kadar . Umarum cin olmadan adam çarpılamayacağını ustandan alıp ustana satamayacağını öğrenmişsindir nitekim şu son yorumun bile benimkinin kopyası

**Comment by necoakdogan** [comment]
Mevcut entegrasyon test işleminde başarılı döndürürken canlı ortama geçtiğimizde fail'e yönlendiriryor. Sorunsuzca kullanan var mı acaba? var ise yardımcı olabilir mi?
